# Generated by Django 4.2.9 on 2025-07-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_horarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horarios',
        ),
    ]
