# Generated by Django 4.2.9 on 2025-07-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horario_apertura', models.TimeField(blank=True)),
                ('horario_cierre', models.TimeField(blank=True)),
            ],
        ),
    ]
