# Generated by Django 4.2.9 on 2025-07-25 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='id_equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='canchas.equipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_DT',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='canchas.director_tecnico'),
        ),
    ]
