# Generated by Django 4.2.9 on 2025-07-24 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_calle', models.CharField(max_length=100)),
                ('num_calle', models.IntegerField()),
                ('comuna', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_run', models.IntegerField()),
                ('dv_run', models.CharField(max_length=1)),
                ('pnombre', models.CharField(max_length=50)),
                ('snombre', models.CharField(blank=True, max_length=50)),
                ('appaterno', models.CharField(max_length=50)),
                ('apmaterno', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fecha_nac', models.DateField()),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.direccion')),
            ],
        ),
        migrations.DeleteModel(
            name='Horarios',
        ),
        migrations.AddField(
            model_name='cancha',
            name='id_horario',
            field=models.ManyToManyField(to='canchas.horario'),
        ),
    ]
