# Generated by Django 4.2.9 on 2025-07-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_jugador_id_equipo_alter_equipo_id_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='equipo_ganador',
            field=models.CharField(choices=[('local', 'Local'), ('visita', 'Visita'), ('empate', 'Empate')], max_length=20),
        ),
    ]
