# Generated by Django 4.2.9 on 2025-07-24 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_torneo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha_Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fecha', models.IntegerField()),
                ('dia_inicio_fecha', models.DateField(blank=True)),
                ('dia_final_fecha', models.DateField(blank=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='canchas.torneo')),
            ],
        ),
    ]
