# Generated by Django 4.2.9 on 2025-07-25 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_cancha_direccion_horario_jugador_delete_horarios_and_more'),
        ('canchas', '0003_fecha_campeonato'),
    ]

    operations = [
    ]
