# Generated by Django 4.2.9 on 2025-07-25 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0004_merge_20250725_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director_tec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nun_run', models.IntegerField()),
                ('dv_run', models.CharField(max_length=1)),
                ('P_nombre', models.CharField(max_length=50)),
                ('S_nombre', models.CharField(blank=True, max_length=50)),
                ('Amaterno', models.CharField(max_length=50)),
                ('Nacionalidad', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horario_apertura', models.TimeField(blank=True)),
                ('horario_cierre', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('puntos', models.IntegerField(default=0)),
                ('id_DT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_DT', to='canchas.director_tec')),
            ],
        ),
    ]
