# Generated by Django 4.2.9 on 2025-07-25 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0005_director_tec_horarios_equipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horarios',
        ),
    ]
