# Generated by Django 4.2.9 on 2025-07-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0006_delete_horarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_run', models.IntegerField()),
                ('dv_run', models.CharField(max_length=1)),
                ('pnombre', models.CharField(max_length=50)),
                ('snombre', models.CharField(max_length=50)),
                ('appaterno', models.CharField(max_length=50)),
                ('apmaterno', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('clima', models.CharField(max_length=50)),
                ('observaciones', models.TextField(max_length=500)),
                ('equipo_ganador', models.CharField(max_length=100)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partido_como_local', to='canchas.equipo')),
                ('equipo_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partido_como_visita', to='canchas.equipo')),
                ('id_arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.arbitro')),
                ('id_cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.cancha')),
                ('id_fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.fecha_campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Director_Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_run', models.IntegerField()),
                ('dv_run', models.CharField(max_length=1)),
                ('pri_nombre', models.CharField(max_length=20)),
                ('sec_nombre', models.CharField(blank=True, max_length=20)),
                ('pri_apellido', models.CharField(max_length=20)),
                ('sec_apellido', models.CharField(blank=True, max_length=20)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('correo_electronico', models.EmailField(max_length=30, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.direccion')),
            ],
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_DT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_DT', to='canchas.director_tecnico'),
        ),
        migrations.DeleteModel(
            name='Director_tec',
        ),
    ]
