# Generated by Django 4.2.9 on 2025-07-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0006_delete_horarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('amarilla', 'Amarilla'), ('roja', 'Roja')], max_length=10)),
                ('minuto', models.IntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica_Jugador_Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_goles', models.IntegerField(default=0)),
                ('total_amarillas', models.IntegerField(default=0)),
                ('total_rojas', models.IntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Director_Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_run', models.IntegerField()),
                ('dv_run', models.CharField(max_length=1)),
                ('pri_nombre', models.CharField(max_length=20)),
                ('sec_nombre', models.CharField(blank=True, max_length=20)),
                ('pri_apellido', models.CharField(max_length=20)),
                ('sec_apellido', models.CharField(blank=True, max_length=20)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('correo_electronico', models.EmailField(max_length=30, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('id_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.direccion')),
            ],
        ),
        migrations.AlterField(
            model_name='equipo',
            name='id_DT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_DT', to='canchas.director_tecnico'),
        ),
        migrations.DeleteModel(
            name='Director_tec',
        ),
    ]
